name = "dmarcheck"
main = "src/index.ts"
compatibility_date = "2025-03-30"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "dmarcheck.cortech.online", custom_domain = true },
]

[dev]
port = 8790
